### PR TITLE
Add hashCode benchmarks

### PR DESCRIPTION
**Pull request by alejandropg**

### CODE REVIEW

**Comment by alejandropg** [comment]
Hi @jamesbassett 

I see that with this PR Travis fails because the maximum job time is exceeded (https://travis-ci.com/github/alejandropg/kassava-benchmarks/builds/164870527)

I suggest change Travis configuration to do less iteration, for example:

`script: mvn clean package && java -jar target/benchmarks.jar -wi 5 -i 3 -f 1 -tu ns -bm avgt`

Just 5 for warmup and 3 for benchmark

What do you think?

**Comment by jamesbassett** [comment]
Sure thing :)

**Comment by alejandropg** [comment]
Ok, now Travis looks good 👍

https://travis-ci.com/github/alejandropg/kassava-benchmarks

**Comment by alejandropg** [comment]
Hi @jamesbassett 

What do you think now? Is it correct or do you need I change something?

Thanks!

**Comment by jamesbassett** [comment]
No I think it's fine :) I'll merge now. The results are a little different but generally the same trend - but so many things have changed since the last benchmark (java, kotlin, potentially the travis host specs) so not really easy to compare. A little worried about the error rate on `apacheReflectionEquals` but meh.

Thanks for the contribution!

**Comment by alejandropg** [comment]
Thanks 👍

Yes, I think that the idea is to reduce Travis time (I think to all the the process in Travis is just a kind of "test", so is very good to do it), but to get real metrics is preferred the complete process.

In fact I did't change the README, because I think is a better recommendation run the complete process to get the real benchmark.

**Pull request merged**
